### ISSUE TITLE
mongo复制集

### ISSUE THREAD

**Issue by terry8210** [FlourishingWorld/hk4e#14]
能否提供mongo复制集的docker部署方式。

**Comment by FlourishingWorld** [comment]
抱歉个人原因暂时没有太多时间完善这个，不过docker/3rd/mongo/mongo_cluster下有提供分片集群的部署模板，希望对你有帮助。

**Comment by terry8210** [comment]
有需要可以补充到项目中，其实也没有必要用分片。
#!/bin/bash

# 安装Docker和Docker Compose
sudo yum update -y
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose
sudo systemctl start docker
sudo systemctl enable docker

# 创建数据目录
sudo mkdir -p /data/mongodb1
sudo mkdir -p /data/mongodb2
sudo mkdir -p /data/mongodb3

# 编写Docker Compose配置文件
cat << EOF > docker-compose.yml
version: '3'
services:
  primary:
    image: mongo
    container_name: mongodb-primary
    restart: always
    volumes:
      - /data/mongodb1:/data/db
    ports:
      - 27017:27017
    command: mongod --replSet myReplicaSet --bind_ip_all
  secondary1:
    image: mongo
    container_name: mongodb-secondary1
    restart: always
    volumes:
      - /data/mongodb2:/data/db
    ports:
      - 27018:27017
    command: mongod --replSet myReplicaSet --bind_ip_all
  secondary2:
    image: mongo
    container_name: mongodb-secondary2
    restart: always
    volumes:
      - /data/mongodb3:/data/db
    ports:
      - 27019:27017
    command: mongod --replSet myReplicaSet --bind_ip_all
EOF

# 启动MongoDB容器并初始化复制集
sudo docker-compose up -d
sleep 10
sudo docker exec mongodb-primary mongo --eval "rs.initiate({_id: 'myReplicaSet', members: [{_id: 0, host: 'mongodb-primary:27017', priority: 2}, {_id: 1, host: 'mongodb-secondary1:27017', priority: 1}, {_id: 2, host: 'mongodb-secondary2:27017', priority: 0}]})"

# 验证复制集状态
sudo docker exec mongodb-primary mongo --eval "rs.status()"

# 完成部署
echo "MongoDB Replica Set deployment completed."
