### ISSUE TITLE
protoc-gen-go

### ISSUE THREAD

**Issue by wdfky** [FlourishingWorld/hk4e#2]
/protocol/cmd/cmd_id_proto_obj_map.go中导入的是pb "google.golang.org/protobuf/proto"
而makefile中是 go install github.com/golang/protobuf/protoc-gen-go@v1.5.2 ，是不是应当=改换为go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

**Comment by FlourishingWorld** [comment]
确实是有natsrpc和游戏proto协议版本不一致的问题，但实际上用旧版本和新版本都可以正常编译运行，找个时间统一一下版本
