### ISSUE TITLE
已经部署好了，如何注册用户？

### ISSUE THREAD

**Issue by 932521665** [FlourishingWorld/hk4e#8]
太羞耻了，都会部署，不会注册个用户，人麻了

**Comment by 932521665** [comment]
![image](https://user-images.githubusercontent.com/31720689/227698721-acef7952-78be-41b3-a18d-e6034a979686.png)

**Comment by sixiwenwu** [comment]
不是自动注册吗，用户名填“用户名@@密码”，密码随便填

**Comment by 932521665** [comment]
> 不是自动注册吗，用户名填“用户名@@密码”，密码随便填

谢谢回复。
后边看到了，所以关了issuse，有个地方500.
https://github.com/FlourishingWorld/hk4e/issues/9

有点难顶
